### ISSUE TITLE
How to build a Windows installer in GitHub Actions

### ISSUE THREAD

**Issue by yutaro-sakamoto** [opensourcecobol/opensourcecobol4j#394]
生成AIである[Claude](https://claude.ai/chats)に、
```
msbuildコマンドを使用してビルドできるc言語で書かれたCLIツールがあります。
このツールの開発では、GitHub Actionsを使ったCI/CD環境を利用しています。
GitHub ActionsでこのCLIツールのインストーラを作成して、Artifactとしてダウンロードするワークフローファイルを出力してください。
```
という質問をしてみました。以下はその回答です。
@kio-watanabe 今後のWindows版開発の参考にしましょう。

# 回答
確かに、GitHub ActionsでC言語のCLIツールのインストーラを作成し、Artifactとしてダウンロードするワークフローファイルを作成することができます。以下が一例です。

```yaml
name: Build and Package CLI Tool

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build CLI Tool
      run: msbuild /p:Configuration=Release MySolutionName.sln
      
    - name: Create Installer
      run: |
        $installer = "MySoftwareName_${env:GITHUB_SHA}.msi"
        $wixToolsPath = "${env:ProgramFiles(x86)}\WiX Toolset v3.11\bin"
        . "$($wixToolsPath)\heat.exe" dir "$(Get-Location)\bin\Release" -srd -cg CliGroup -dr INSTALLFOLDER -out heat.wxs
        . "$($wixToolsPath)\candle.exe" -dCliToolSourceDir="$(Get-Location)\bin\Release" heat.wxs
        . "$($wixToolsPath)\light.exe" heat.wixobj -ext WixUIExtension -cultures:null -dWixUILicenseRtf="$(Get-Location)\License.rtf" -out $installer
        Write-Host "Installer created: $installer"
        
    - uses: actions/upload-artifact@v3
      with:
        name: Installer
        path: MySoftwareName_${{ github.sha }}.msi
        
```

このワークフローは、以下の手順を実行します。

1. `windows-latest`ランナー環境でジョブを実行します。
2. リポジトリをチェックアウトします。
3. `setup-msbuild`アクションを使用して、MSBuildをPATHに追加します。
4. `msbuild`コマンドを使用して、リリース構成でCLIツールをビルドします。
5. WiXツールセットを使用してインストーラ(MSI)を作成します。
6. 作成したインストーラをArtifactとしてアップロードします。

WiXツールセットは、Windowsの場合、インストーラ作成によく使われるツールセットです。このワークフローでは、`heat.exe`を使ってCLIツールのファイルをマッピングし、`candle.exe`と`light.exe`を使ってMSIインストーラを作成しています。

ご要望に合わせて、適宜変更を加えてください。例えば、インストーラのプロパティやアイコンの設定、インストーラの命名規則の変更などが考えられます。
